#!/bin/bash
#
# Copyright 2014 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#  http://aws.amazon.com/apache2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# This is an appspec.yml template file for use with AWS CodeDeploy.
# For help completing this file, see the "AppSpec File Reference" in the  
#   "AWS CodeDeploy User Guide" at
#   http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html

# do not change version, this is controlled by AWS
version: 0.0
os: linux 
files:
  - source: /
    destination: /var/www/html
permissions:
  - object: /var/www/html
    pattern: "*.html"
    owner: root
    group: root
    mode: 755
  - object: /var/www/html/scripts
    pattern: "*.sh"
    owner: root
    group: root
    mode: 700
hooks:
  ApplicationStop:
    - location: scripts/deregister_from_elb.sh
      timeout: 180
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start_httpd.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: scripts/validate_me.sh
      timeout: 60
      runas: root
    - location: scripts/register_with_elb.sh
      timeout: 180
      runas: root
